name: Run Test with Pretest-API dependency

on:
  push:
    branches:
      - '*'

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clone server repository
        run: git clone --depth=1 https://github.com/dosemedia/pretest-api.git

      - name: Start containers
        run: |
          cd pretest-api
          docker-compose -f ./docker-compose.test.yaml up -d

      - name: Modify variable and start server
        run: |
          cd pretest-api
          sed -i 's#DATABASE_URL=postgres://postgres:pgadmin@localhost:5432/postgres?schema=public#DATABASE_URL=postgres://postgres:pgadmin@localhost:5433/postgres?schema=public#g' ./.env
          yarn install
          yarn prisma generate
          yarn dev
          

      - name: Wait for server to start
        run: sleep 10 # Adjust this based on the time required for the server to start

      - name: Run yarn test
        run: |
          yarn install
          yarn test
