name: Run Test with Pretest-API dependency

on:
  push:
    branches:
      - brady-test

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run yarn test
        run: |
          yarn install
          yarn codegen
          yarn test
