name: Run Test with Pretest-API dependency

on:
  push:
    branches:
      - brady-test

jobs:
  run-tests:
    runs-on: ubuntu-latest
    env:
      NODE_BASE_URL: ${{ secrets.NODE_BASE_URL }}
      HASURA_GRAPHQL_ADMIN_SECRET:  ${{ secrets.HASURA_GRAPHQL_ADMIN_SECRET }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      VITE_HASURA_BASE_URL:  ${{ secrets.VITE_HASURA_BASE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug Environment Variables
        run: |
          echo "NODE_BASE_URL: $NODE_BASE_URL"
          echo "HASURA_GRAPHQL_ADMIN_SECRET: $HASURA_GRAPHQL_ADMIN_SECRET"
          echo "DATABASE_URL: $DATABASE_URL"
          echo "VITE_HASURA_BASE_URL: $VITE_HASURA_BASE_URL"

      - name: Clone server repository
        run: git clone --depth=1 https://github.com/dosemedia/pretest-api.git

      - name: Start containers
        run: |
          cd pretest-api
          docker-compose -f ./docker-compose.test.yaml up -d
          docker ps

      - name: Modify variable and start server
        run: |
          cd pretest-api
          yarn install
          yarn start

      - name: Sleep
        run: sleep 30s

      - name: Run yarn test
        run: |
          yarn install
          yarn codegen
          yarn test
