name: Run Test with Pretest-API dependency

on:
  push:
    branches:
      - '*'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    env:
      NODE_BASE_URL: ${{ secrets.NODE_BASE_URL }}
      HASURA_GRAPHQL_ADMIN_SECRET: ${{ secrets.HASURA_GRAPHQL_ADMIN_SECRET }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      VITE_HASURA_BASE_URL: ${{ secrets.VITE_HASURA_BASE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug NODE_BASE_URL
        run: echo $NODE_BASE_URL

      - name: Clone server repository
        run: git clone --depth=1 https://github.com/dosemedia/pretest-api.git

      - name: Start containers
        run: |
          cd pretest-api
          docker-compose -f ./docker-compose.test.yaml up -d

      - name: Modify variable and start server
        run: |
          cd pretest-api
          yarn install
          yarn prisma generate
          yarn start

      - name: Run yarn test
        run: |
          yarn install
          yarn build
          yarn test
